export const HERO_DEFAULT_STAT = {
  LEVEL: 1,
  EXPERIENCE: 0,
  MAX_HP: 100,
  CURRENT_HP: 100,
  MAX_MP: 100,
  CURRENT_MP: 100,
  STRENGTH: 10,
  INTELLIGENCE: 10,
  DEXTERITY: 10,
  DODGE: 0,
  CRITICAL: 0,
  PHYSICAL_ATTACK: 10,
  MAGICAL_ATTACK: 10,
  PHYSICAL_DEFENSE: 10,
  MAGICAL_DEFENSE: 10,
  FATIGUE: 0,
  MAX_DAILY_TODO_REWARD: 10,
  RECEIVED_DAILY_TODO_REWARD: 0,
  MAX_WEEKLY_TODO_REWARD: 3,
  RECEIVED_WEEKLY_TODO_REWARD: 0,
} as const;

export const MAX_FATIGUE = 100;
